App/urls.py
from re import I
from unicodedata import name
from django.urls import path
from . import views
from .views import Kurti_Index, Trousers_Index, Cart, CheckOut, Index

app_name = 'App'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('login/', views.loginuser, name='login'),
    path('register/', views.register, name='register'),
    path("logout", views.logoutuser, name= "logout"),
    path("categories/", views.categories, name= "categories"),
    path("categories/Kurti/", Kurti_Index.as_view(), name= "kurti"),
    path("categories/Trousers/", Trousers_Index.as_view(), name= "trousers"),
    path("cart", Cart.as_view(), name= "cart"),
    path("checkout", CheckOut.as_view(), name= "checkout"),
    path("add_products", views.add_products, name='add_products'),
    path("see_orders", views.see_orders, name='see_orders')
    
]

Shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls'))
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

App/templates/App/add_products.html
{% extends 'App/base.html' %}

{% block body %}
<div class="container py-4">
<form action="/add_products", method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    <label for="name">Product name:</label>
    <input type="text" name="name"><br>

    <label for="image">Select image:</label>
    <input type="file" name="image" accept="image/*"><br>

    <label for="type">Product Type</label><br>
    <input type="radio" name="types" value="Kurti">
    <label for="Kurti">Kurti</label><br>
    <input type="radio"name="types" value="Trousers">
    <label for="Trousers">Trousers</label><br>

    <label for="price">Price</label>
    <input type="text" name="price"><br><br>
    <input type="submit" class="btn btn-dark value="Submit"">
  </form> 
</div>
{% endblock body %}

App/templates/App/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="{% static 'App/css/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block top %}
    {% endblock top %}
  <title>Tooba Shop</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
<a class="navbar-brand" href="/">Tooba Shop</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App:categories' %}">Poduct Categories</a>
          </li>
          {% if user.username == 'admin' %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App:add_products' %}">Add Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App:see_orders' %}">Orders</a>
          </li>{% endif %}
        </ul> 
        <a href={% url 'App:cart' %}><img src="{% static "App/images/cart.jpg" %}" alt="cart" style="width:30px;"></a>
        {% if user.is_authenticated %}
        <p style="color: white;"> Welcome, {{user.username}}</p>
        <a href="{% url 'App:logout' %}" class="btn btn-light transition-hover btn-lg ml-3">Logout</a>
        {%else%}
        <a href="{% url 'App:login' %}" class="btn btn-light transition-hover btn-lg ml-3">Sign In</a>
        <a href="{% url 'App:register' %}" class="btn btn-light transition-hover btn-lg ml-3">Sign Up</a>
        {%endif%}
      </div>
    </nav>
</header>
<body>
    {% block body %}{% endblock body %}
</body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>    
</body>
</html>

App/templates/App/cart.html
{% extends 'App/base.html' %}

{% block body %}
{% load cart %}
{% load custom_filter %}

{% if products %}
{% if paths %}

<div class="container">
    <div class="border rounded p-4 m-4">
         <p class="display-4 pl-4 ml-4">Your Cart</p>
         <hr>
         <table class="table">
             <thead>
                 <tr>
                     <th scope="row">Sno.</th>
                     <th>Image</th>
                     <th>Product</th>
                     <th>Price</th>
                     <th>Quantity</th>
                     <th>Total</th>
                 </tr>
             </thead>
             <tbody>
                 
                 {% for product in products %}
                 <tr>
                     <td scope="row">{{forloop.counter}}</td>
                     <td><img style="height: 80px;" class="rounded-circle" src="{{paths}}/{{product.product_image}}" alt=""></td>
                     <td>{{product.product_name}}</td>
                     <td>{{product.price|currency}}</td>
                     <td>{{product|cart_quantity:request.session.cart}}</td>
                     <td>{{product|price_total:request.session.cart|currency}}</td>
                 </tr>
 
                 {% endfor %}
                
             </tbody>
 
             <tfoot>
                 <tr>
                     <th colspan="4"></th>
                     <th class="" colspan="">Total</th>
                     <th>{{products|total_cart_price:request.session.cart|currency}}</th>
                 </tr>
             </tfoot>
         </table>
         <hr>
         <div class="m-3 p-3">
            <a href="{% url 'App:checkout' %}" class="btn btn-outline-info border rounded  col-lg-3 float-right">Check out</a>
        </div>
   </div>
</div>

{% endif %}
{% else %}
<div class="container">
    <div class="border rounded p-4 m-4">
         <p class="display-4 pl-4 ml-4">Your Cart</p>
            <h5 class="pl-4 ml-4"> Your cart is empty</h5>
    </div>
</div>
{% endif %}


{% endblock body %}

App/templates/App/categories.html
{% extends 'App/base.html' %}

{% block body %}

{% if product_categories %}
<div class="container py-3">
<ul>
{% for categories in product_categories%}
<li><a href={{categories}}>{{categories}}</a></li>
{% endfor %}

</ul>
</div>
{% endif %}

{% endblock body %}

App/templates/App/checkout.html
{% extends 'App/base.html' %}

{% block body %}

<form action="{{CheckOut}}" method="POST">
    {% csrf_token %}

      <input type="submit" class="btn float-right btn-outline-info col-lg-6" value="Check out">
</form>
{% comment %} <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">
              Check Out Form
          </h5>
          <hr>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="m-2 p-3">
            <form action="{{CheckOut}}" method="POST">
                {% csrf_token %}
                {% comment %} <div class="form-group">
                  <label for="">Address</label>
                  <input type="text" name="address" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  
                </div>
                <div class="form-group">
                    <label for="">Phone</label>
                    <input type="text" name="phone" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  </div> {% endcomment %}
{% comment %} 
                  <input type="submit" class="btn float-right btn-outline-info col-lg-6" value="Check out">
            </form>
          </div>
        </div>
        
      </div>
    </div>
  </div> {% endcomment %}

{% endblock body %}

App/templates/App/index.html
{% extends 'App/base.html' %}
{% block body %}
{% load cart %}
{% load custom_filter %}

<div class="container-fluid mt-3">
	<div class="row">
		{% if paths %}
		{% if products %}

		<div id='products' class="col-lg-9 mx-auto">
			<div class="row mx-auto">
				{% for product in products %}
				<div class="card mx-auto mb-3" style="width: 18rem;">
					<img class="card-img-top" src="{{paths}}/{{product.product_image}}" alt="Card image cap" style="width:80%; height:300px;">
					<div class="card-body">
						<h5 class="card-title">{{product.product_name}}</h5>
						<p class="card-text">Price <em><b>{{product.price}}</b></em></p>
						<form action="{{Kurti}}" method="POST" class="btn-block">
							{% csrf_token %}
							<input hidden type="text" name='product' value='{{product.product_id}}'>
							<input type="submit" class="float-right btn btn-dark  form-control"
								value="Add To Cart">
						
						</form>
					</div>

				</div>
				{% endfor %}
				{% endif %}
				{% endif %}
			</div>
		</div>
	</div>
</div>

{% endblock body %}

App/templates/App/kurti.html
{% extends 'App/base.html' %}
{% block body %}
{% load cart %}
{% load custom_filter %}

<div class="container-fluid mt-3">
	<div class="row">
		{% if paths %}
		{% if kurtis %}

		<div id='products' class="col-lg-9 mx-auto">
			<div class="row mx-auto">
				{% for product in kurtis %}
				<div class="card mx-auto mb-3" style="width: 18rem;">
					<img class="card-img-top" src="{{paths}}/{{product.product_image}}" alt="Card image cap" style="width:80%; height:300px;">
					<div class="card-body">
						<h5 class="card-title">{{product.product_name}}</h5>
						<p class="card-text">Price <em><b>{{product.price}}</b></em></p>
						<form action="{{Kurti}}" method="POST" class="btn-block">
							{% csrf_token %}
							<input hidden type="text" name='product' value='{{product.product_id}}'>
							<input type="submit" class="float-right btn btn-dark  form-control"
								value="Add To Cart">
						
						</form>
					</div>

				</div>
				{% endfor %}
				{% endif %}
				{% endif %}
			</div>
		</div>
	</div>
</div>

{% endblock body %}

App/templates/App/login.html
{% extends 'App/base.html' %}

{% block body %}
{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <br>
    <button class="btn btn-dark" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>
{% endblock body %}

App/templates/App/register.html
{% extends 'App/base.html' %}

{% block body %}
{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}  
		                  
		<button class="btn btn-dark" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>
{% endblock body %}

App/templates/App/see_orders.html
{% extends 'App/base.html' %}

{% block body %}
<style>
    table, th, td ,tr{
      border:1px solid black;
    }
</style>
    
{% if orders %}
<div class="container py-4">    
<h5>All Orders</h5>
{% if order_items %}

<table>
    <tr>
      <th>Orders</th>
      <th>Customer_name</th>
      <th>Product_name</th>
      <th>Quantity</th>
      <th>Completed</th>
    </tr>
    {% for i in order_items %}
    <tr>
      {% comment %} <td>{{i.order_id.order_id}}</td> {% endcomment %}
      <td>{{forloop.counter}}</td>
      <td>{{i.order_id.user_id}}</td>
      <td>{{i.product_id}}</td>
      <td>{{i.quantity}}</td>
      <td>{{i.order_id.completed}}</td>
    </tr><br>
    {% endfor %}
  </table>
</div>

{% endif %}
{% endif %}
{% endblock body %}

App/templates/App/trousers.html
{% extends 'App/base.html' %}
{% block body %}
{% load static %}

{% load cart %}
{% load custom_filter %}

<div class="container-fluid mt-3">
	<div class="row">
		{% if paths %}
		{% if trousers %}

		<div id='products' class="col-lg-9 mx-auto">
			<div class="row mx-auto">
				{% for product in trousers %}
				<div class="card mx-auto mb-3" style="width: 18rem;">
					<img class="card-img-top" src="{{paths}}/{{product.product_image}}" alt="Card image cap" style="width:80%; height:300px;">
					<div class="card-body">
						<h5 class="card-title">{{product.product_name}}</h5>
						<p class="card-text">Price <em><b>{{product.price}}</b></em></p>

						<form action="{{Trousers}}" method="POST" class="btn-block">
							{% csrf_token %}
							<input hidden type="text" name='product' value='{{product.product_id}}'>
							<input type="submit" class="float-right btn btn-dark  form-control"
								value="Add To Cart">
						</form>
					</div>

				</div>
				{% endfor %}
				{% endif %}
				{% endif %}
			</div>
		</div>
	</div>
</div>

{% endblock body %}